---
version: '3'
services:
  umami:
    image: ghcr.io/umami-software/umami:postgresql-latest
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgresql://postgres:Tendy1234@pg.trellisinsights.com:5432/hibuddy
      DATABASE_TYPE: postgresql
      HASH_SALT: replace-me-with-a-random-string

    restart: always


